"""Bundle a multi-file Lua pack into the single string Risu expects.

Risu accepts one Lua string (the ``${code}`` spliced into ``luaCodeWrapper``)
and gives user code no way to mount its own files. So a multi-file pack is
amalgamated into one self-contained module system:

    local __modules, __loaded = {}, {}
    local function __require(name) ... end       -- falls back to host require()
    __modules['utils'] = function(require) ... end
    __modules['main']  = function(require) ... end
    __require('main')

Each module loader takes a ``require`` parameter that shadows the global, so
``require('utils')`` inside a module resolves to ``__require``. Unknown names
(e.g. ``'json'``) defer to Risu's own ``require``. The entry module runs last;
its top-level ``function onStart(id)`` etc. become the globals Risu dispatches.
"""
from __future__ import annotations

import json as _json
import os
from typing import Dict, Tuple

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError as exc:  # pragma: no cover
    raise RuntimeError("luapack requires Python 3.11+ (for tomllib)") from exc


class BundleError(Exception):
    pass


# Local module runtime prepended to every bundle.
_RUNTIME = """local __modules = {}
local __loaded = {}
local function __require(name)
    local cached = __loaded[name]
    if cached then return cached.v end
    local loader = __modules[name]
    if loader == nil then
        return require(name)  -- defer to the host (e.g. 'json')
    end
    local result = loader(__require)
    if result == nil then result = true end
    __loaded[name] = { v = result }
    return result
end"""


def _lua_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def load_config(pack_dir: str) -> Dict:
    path = os.path.join(pack_dir, "luapack.toml")
    cfg = {}
    if os.path.exists(path):
        with open(path, "rb") as fh:
            cfg = tomllib.load(fh)
    pack = cfg.get("pack", {}) if isinstance(cfg, dict) else {}
    return {
        "name": pack.get("name", os.path.basename(os.path.abspath(pack_dir))),
        "entry": pack.get("entry", "main"),
        "src": pack.get("src", "src"),
        "out": pack.get("out", os.path.join("dist", "bundle.lua")),
        "low_level_access": bool(pack.get("low_level_access", False)),
    }


def discover_modules(src_dir: str, display_base: str = None) -> Dict[str, Dict]:
    """Map every ``*.lua`` under ``src_dir`` to a dotted module name.

    Module names are relative to ``src_dir``; the ``path`` stored for markers and
    the source map is relative to ``display_base`` (the pack dir) when given, so
    errors point at e.g. ``src/utils.lua`` rather than just ``utils.lua``.
    """
    mods: Dict[str, Dict] = {}
    for root, _dirs, files in os.walk(src_dir):
        for fn in sorted(files):
            if not fn.endswith(".lua"):
                continue
            full = os.path.join(root, fn)
            rel = os.path.relpath(full, src_dir).replace(os.sep, "/")
            name = rel[:-4]  # strip '.lua'
            if name.endswith("/init"):
                name = name[: -len("/init")]  # foo/init.lua -> 'foo'
            modname = name.replace("/", ".")
            disp = os.path.relpath(full, display_base or src_dir).replace(os.sep, "/")
            with open(full, "r", encoding="utf-8") as fh:
                mods[modname] = {"path": disp, "source": fh.read()}
    return mods


def build_bundle(modules: Dict[str, Dict], entry: str, pack_name: str) -> Tuple[str, Dict]:
    if entry not in modules:
        raise BundleError(
            f"entry module '{entry}' not found; modules: {sorted(modules)}"
        )

    lines = [
        f"-- luapack bundle: {pack_name} (entry: {entry})",
        "-- Generated by luapack. Paste into Risu's Lua trigger field.",
        "",
    ]
    lines.extend(_RUNTIME.split("\n"))
    lines.append("")

    module_map: Dict[str, Dict] = {}
    for modname in sorted(modules):
        m = modules[modname]
        lines.append(f"-- <<< {m['path']} >>>")
        lines.append(f"__modules[{_lua_str(modname)}] = function(require)")
        src_lines = m["source"].rstrip("\n").split("\n")
        start_line = len(lines) + 1  # 1-based line of the module's first source line
        lines.extend(src_lines)
        module_map[modname] = {
            "path": m["path"],
            "start_line": start_line,
            "lines": len(src_lines),
        }
        lines.append("end")
        lines.append("")

    lines.append(f"__require({_lua_str(entry)})")
    bundle = "\n".join(lines) + "\n"
    return bundle, module_map


def build_pack(pack_dir: str) -> Dict:
    """Build a pack in memory (no files written)."""
    cfg = load_config(pack_dir)
    src_dir = os.path.join(pack_dir, cfg["src"])
    if not os.path.isdir(src_dir):
        raise BundleError(f"source directory not found: {src_dir}")
    raw = discover_modules(src_dir, display_base=pack_dir)
    if not raw:
        raise BundleError(f"no .lua files found under {src_dir}")
    bundle, module_map = build_bundle(raw, cfg["entry"], cfg["name"])
    return {
        "bundle": bundle,
        "out": os.path.join(pack_dir, cfg["out"]),
        "modules": module_map,
        "config": cfg,
    }


def write_pack(pack_dir: str) -> Dict:
    """Build a pack and write ``dist/bundle.lua`` plus a ``.map.json`` sidecar."""
    res = build_pack(pack_dir)
    out = res["out"]
    out_dir = os.path.dirname(os.path.abspath(out))
    os.makedirs(out_dir, exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(res["bundle"])
    with open(out + ".map.json", "w", encoding="utf-8", newline="\n") as fh:
        _json.dump(
            {"entry": res["config"]["entry"], "modules": res["modules"]},
            fh,
            indent=2,
        )
    return res
